version: '3.5'

services:
  symfony-api-prueba-web:
    container_name: symfony-api-prueba-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 250:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - symfony-api-prueba-be
    networks:
      - symfony-api-prueba-network

  symfony-api-prueba-be:
    container_name: symfony-api-prueba-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=Docker
      # PHP_XDEBUG_ENABLED: 1
      # XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005 # Linux users
      # XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9005 # MacOS users
    volumes:
      - ./:/appdata/www
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # - ./docker/php/xdebug-macos.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - symfony-api-prueba-db
    networks:
      - symfony-api-prueba-network

  symfony-api-prueba-db:
    container_name: symfony-api-prueba-db
    build:
      context: ./docker/database
    image: mysql:8.0  
    ports:
      - 36000:3306
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - symfony-api-prueba-db-data:/var/lib/mysql
    networks:
      - symfony-api-prueba-network

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  symfony-api-prueba-db-data:

networks:
  symfony-api-prueba-network:
    external: true
