# controllers:
#     resource:
#         path: ../src/Api/
#         namespace: App\Controller
#     type: attribute

controllers:
    resource:
        path: ../src/Api/Action
        namespace: App\Api\Action
        prefix: v1
    type: annotation
