<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5UVf2GH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5UVf2GH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5UVf2GH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5UVf2GH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5UVf2GH\App_KernelDevDebugContainer([
    'container.build_hash' => '5UVf2GH',
    'container.build_id' => 'be63e84a',
    'container.build_time' => 1703520305,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5UVf2GH');
